spring.application.name=BankMenegmentCard

spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=user
spring.r2dbc.password=pass

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.secret=mySecretKeyForJWTGenerationInProductionChangeThis
spring.security.oauth2.resourceserver.jwt.expiration=86400

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swgger-ui.html
springdoc.swagger-ui.operations-sorter=method
